version: '3.7'
services:
  backend:
      build: ./backend/
      env_file:
      - ./backend/.env
      ports:
        - ${PORT}:${PORT}
      depends_on:
        - database
      volumes:
        - ./backend:/usr/src/app

  database:
    image: postgres:latest
    restart: always 
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: ecommerce

    ports:
      - '5433:${DB_PORT}'

    volumes:
      -  data:/data/database
      - ./database:/docker-entrypoint-initdb.d

volumes:
  data: {}